/* ═══════════════════════════════════════════════════════════
   B.U.G. — shared chrome
   Injects the header and drawer into #chrome-mount and wires
   everything. One copy, every page.

   Each page declares its identity on <body>:
     <body data-page="home">      speaker = ambient audio toggle
     <body data-page="catalog">   speaker = home link
   ═══════════════════════════════════════════════════════════ */

/* ═══════════════════════════════════════════════════════════
   RESPONSIVE IMAGES

   Every referenced raster image has a 900px sibling generated by
   variants.sh — foo.jpg alongside foo-900.jpg. This builds the
   srcset so a phone fetches the small one.

   Generated for ALL referenced images rather than a subset, so
   this can be applied unconditionally without checking whether a
   given variant exists.
   ═══════════════════════════════════════════════════════════ */

/* ═══════════════════════════════════════════════════════════
   HELD RELEASES

   A record with `releaseAt` in the future is carried but not
   revealed: the artwork is boxed out and the title censored.
   The register holds a thing before it is issued; it does not
   pretend the thing is absent.
   ═══════════════════════════════════════════════════════════ */
window.bugHeld = function (r) {
  return !!(r && r.releaseAt && Date.now() < new Date(r.releaseAt).getTime());
};

window.bugCountdown = function (iso) {
  const ms = new Date(iso).getTime() - Date.now();
  if (ms <= 0) return '';
  const d = Math.floor(ms / 86400000);
  const h = Math.floor(ms % 86400000 / 3600000);
  const m = Math.floor(ms % 3600000 / 60000);
  const s = Math.floor(ms % 60000 / 1000);
  const p = n => String(n).padStart(2, '0');
  return d > 0 ? `${d}d ${p(h)}:${p(m)}:${p(s)}` : `${p(h)}:${p(m)}:${p(s)}`;
};

window.bugSrcset = function (p) {
  if (!p) return '';
  const i = p.lastIndexOf('.');
  if (i < 0) return '';
  const ext = p.slice(i + 1).toLowerCase();
  if (ext === 'svg' || ext === 'gif') return '';   // vector / animated: one file only
  return p.slice(0, i) + '-900.' + p.slice(i + 1) + ' 900w, ' + p + ' 2200w';
};

(() => {
  'use strict';

  const PAGE    = document.body.dataset.page || '';
  const IS_HOME = PAGE === 'home';

  const NAV = [
    { label: 'MEDIA',   href: 'media',   id: 'media'   },
    { label: 'CATALOG', href: 'catalog', id: 'catalog' },
    { label: 'PROGRAM', href: 'program', id: 'program' },
    { label: 'INFO',    href: 'info',    id: 'info'    }
  ];


  /* `label` is used verbatim in the bar when present, so a record can
     read exactly as it should rather than being assembled from parts. */
  const PLAYLIST = [
    { label: 'Teton Eternal - Miracle! (BUG.WRKS.003&bull;2026) [37:49]',
      /* until this moment the bar carries the record struck out and
         counting, and the track will not play */
      releaseAt: '2026-09-17T00:00:00-07:00',
      heldLabel: 'Teton Eternal - <i class="redact">________</i> (BUG.WRKS.003&bull;2026)',
      title: 'Miracle!', artist: 'Teton Eternal', duration: '37:49',
      src: 'assets/audio/teton-eternal-miracle.mp3' }
  ];

  /* ── build ─────────────────────────────────────────────── */
  const active = id => id === PAGE ? ' class="is-active"' : '';
  const navHTML = NAV.map(n => `<a href="${n.href}"${active(n.id)}>${n.label}</a>`).join('\n        ');

  const mount = document.getElementById('chrome-mount');
  if (!mount) return;

  mount.outerHTML = `
  <div id="chrome">

    <button id="burger" aria-label="Open menu" aria-expanded="false" aria-controls="menu">
      <span></span><span></span><span></span>
    </button>

    <div id="nav-wrap">
      <nav>
        ${navHTML}
      </nav>
    </div>

    <div id="speaker-wrap">
      <button id="speaker-toggle" aria-label="${IS_HOME ? 'Sound off' : 'Home'}"${IS_HOME ? ' aria-pressed="false"' : ''}>
        <img id="speaker-img" src="assets/speakerflag.svg" alt="">
      </button>
    </div>

    <div id="stack-wrap">
      <div id="stack">
        <div class="row sub-row">
          <a id="subscribe-link" href="subscribe">subscribe</a>
        </div>
        <div class="row">
          <div class="input-wrap">
            <input type="text" id="search-input" autocomplete="off" spellcheck="false">
            <span id="search-dots" aria-hidden="true"><i>.</i><i>.</i><i>.</i></span>
          </div>
          <button id="search-btn">search</button>
        </div>
        <div id="stream-row">
          <div id="stream-title">&mdash;</div>
          <button id="stream-mute" aria-label="Unmute stream" aria-pressed="false">
            <img id="stream-mute-img" src="assets/off.svg" alt="">
          </button>
        </div>
      </div>
    </div>

  </div>`;

  /* ── site foot ──────────────────────────────────────────
     Official business name, contact and policy links, on every
     page. Carriers inspect the footer when verifying a brand,
     and its absence was cited in the first 10DLC rejection. */
  const foot = document.createElement('footer');
  foot.id = 'site-foot';
  foot.innerHTML = `
    <div class="name">BEAUTIFUL UNITY GYMNASIUM</div>
    <div>Label, collective, studio, entity &middot; Portland, Oregon, United States</div>
    <div><a href="mailto:b.u.gymnasium@gmail.com">b.u.gymnasium@gmail.com</a></div>
    <div class="links">
      <a href="register">Catalog</a>
      <a href="privacy">Privacy Policy</a>
      <a href="terms">Messaging Terms</a>
    </div>`;
  document.body.appendChild(foot);

  document.body.insertAdjacentHTML('beforeend', `
  <div id="menu-scrim"></div>
  <nav id="menu" aria-hidden="true">
    <button id="menu-close" aria-label="Close menu"></button>
    ${navHTML}
    <div class="menu-foot">
      <span class="menu-mark">02.21<i class="dot2">.</i>07</span>
      <img class="rated" src="assets/rated-b.png" alt="">
    </div>
  </nav>`);

  /* ═══════════════════════════════════════════════════════
     CAP CENTRING — measured, not estimated

     All-caps type does not sit centered in its line box: the box
     reserves descender space that capitals never use, so the
     letters ride high. Every inverted block (nav active, drawer
     active, title blocks, link hovers) has to shift by that
     amount to centre on the LETTERS rather than the box.

     The offset is a property of the font's metrics, so rather
     than hardcode a guess it is measured here once the font has
     actually loaded:

       offset_em = ((descent - ascent) / 2 + capHeight / 2) / size

     which is independent of line-height. Result is written to
     --cap-fix and every block reads from it.
     ═══════════════════════════════════════════════════════ */
  function measureCapFix() {
    try {
      const SIZE = 200;
      const c = document.createElement('canvas');
      c.width = SIZE * 2; c.height = SIZE * 3;
      const x = c.getContext('2d', { willReadFrequently: true });
      const stack = getComputedStyle(document.documentElement)
                      .getPropertyValue('--type-cn').trim();
      x.font = `700 ${SIZE}px ${stack}`;
      x.textBaseline = 'alphabetic';
      x.fillStyle = '#000';
      const baseline = SIZE * 2;
      x.fillText('H', 10, baseline);

      const m = x.measureText('H');
      const asc  = m.fontBoundingBoxAscent;
      const desc = m.fontBoundingBoxDescent;
      if (!asc && asc !== 0) return;              // unsupported — keep the CSS default

      // topmost opaque row gives the true cap height
      const d = x.getImageData(0, 0, c.width, c.height).data;
      let capTop = -1;
      outer:
      for (let y = 0; y < c.height; y++) {
        for (let px = 0; px < c.width; px++) {
          if (d[(y * c.width + px) * 4 + 3] > 10) { capTop = y; break outer; }
        }
      }
      if (capTop < 0) return;

      const capH = baseline - capTop;
      const em   = ((desc - asc) / 2 + capH / 2) / SIZE;

      // sanity clamp — a wild value means the measurement went wrong
      if (em > 0.30 || em < -0.30) return;
      document.documentElement.style.setProperty('--cap-fix', em.toFixed(4) + 'em');
    } catch (e) { /* keep the CSS default */ }
  }

  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(measureCapFix);
  } else {
    window.addEventListener('load', measureCapFix);
  }

  /* ── burger ────────────────────────────────────────────── */
  const burger = document.getElementById('burger');
  const menu   = document.getElementById('menu');
  const scrim  = document.getElementById('menu-scrim');

  function setMenu(open) {
    document.body.classList.toggle('menu-open', open);
    menu.classList.toggle('open', open);
    scrim.classList.toggle('open', open);
    burger.setAttribute('aria-expanded', String(open));
    menu.setAttribute('aria-hidden', String(!open));
  }
  burger.addEventListener('click', e => { e.stopPropagation(); setMenu(!menu.classList.contains('open')); });
  scrim.addEventListener('click', () => setMenu(false));
  document.getElementById('menu-close').addEventListener('click', () => setMenu(false));
  document.addEventListener('keydown', e => { if (e.key === 'Escape') setMenu(false); });

  /* ── speaker: ambient toggle on home, home link elsewhere ─ */
  const spkBtn = document.getElementById('speaker-toggle');
  const spkImg = document.getElementById('speaker-img');
  const ambient = document.getElementById('ambient');

  if (IS_HOME && ambient) {
    ambient.muted = true;
    ambient.play().catch(() => {});
    let on = false;
    spkBtn.addEventListener('click', () => {
      on = !on;
      ambient.muted = !on;
      if (on) ambient.play().catch(() => {});
      spkImg.src = on ? 'assets/speakerflag-reverse.svg' : 'assets/speakerflag.svg';
      spkBtn.setAttribute('aria-pressed', String(on));
      spkBtn.setAttribute('aria-label', on ? 'Sound on' : 'Sound off');

      /* master switch — the page's effects follow this, the stream
         bar does not. Announced rather than reached into, so the
         home page owns its own sound. */
      window.dispatchEvent(new CustomEvent('bug:sfx', { detail: { on } }));
    });
  } else {
    spkBtn.addEventListener('click', () => { window.location.href = 'index'; });
  }

  /* ═══════════════════════════════════════════════════════
     STREAM BAR

     Boots muted so autoplay is permitted, which means the audio
     is already running silently and unmutes instantly on click
     with no start-up stall.

     Separate HTML documents means the <audio> element dies on
     every navigation — it cannot be made to survive. What it CAN
     do is resume: track index, playhead and unmuted state are
     written to sessionStorage and restored on the next page. The
     sound drops during load, then picks up where it was.

     Restoring UNMUTED needs the browser to allow audible
     autoplay. It often will once someone has engaged with the
     site, but not always — if play() rejects we fall back to
     muted and set the icon to match, rather than showing an
     unmuted icon over silence.
     ═══════════════════════════════════════════════════════ */
  const stream      = document.getElementById('stream');
  const streamTitle = document.getElementById('stream-title');
  const streamMute  = document.getElementById('stream-mute');
  const streamImg   = document.getElementById('stream-mute-img');
  const STORE = 'bug.stream';

  let trackIndex = 0;
  let streamOn   = false;

  function setStreamIcon() {
    streamImg.src = streamOn ? 'assets/on.svg' : 'assets/off.svg';
    streamMute.setAttribute('aria-pressed', String(streamOn));
    streamMute.setAttribute('aria-label', streamOn ? 'Mute stream' : 'Unmute stream');
  }

  /* one ticker for the bar, started only when something is held */
  let heldTick = null;

  function showTitle(i) {
    if (!PLAYLIST.length) { streamTitle.innerHTML = '<span>&mdash;</span>'; return; }
    const t = PLAYLIST[i];

    const held = window.bugHeld && window.bugHeld(t);
    const text = held
      ? `${t.heldLabel || `${t.artist} - <i class="redact">________</i>`} &nbsp;&mdash;&nbsp; ${window.bugCountdown(t.releaseAt)}`
      : (t.label || `${t.artist} - ${t.title} [${t.duration}]`);

    /* the countdown has to re-render every second; the roll animation
       restarts with it, which is why it is only run while held */
    if (held && !heldTick) {
      heldTick = setInterval(() => {
        if (!window.bugHeld(PLAYLIST[trackIndex])) {
          clearInterval(heldTick); heldTick = null;
        }
        showTitle(trackIndex);
      }, 1000);
    }

    /* Doubled so the loop is seamless: the animation travels exactly
       half the width, at which point the copy sits where the original
       began. A single run would snap back visibly.

       The gap has to sit INSIDE each copy, not after the pair — a
       trailing pad would leave the two runs butted together at the
       loop point and only open a space at the very end. */
    const gap = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
    streamTitle.innerHTML = `<span>${text}${gap}${text}${gap}</span>`;

    /* scroll only if it overflows — measured, not assumed */
    requestAnimationFrame(() => {
      const inner = streamTitle.firstElementChild;
      streamTitle.classList.toggle('roll',
        inner && inner.scrollWidth / 2 > streamTitle.clientWidth + 2);
    });
  }

  function loadTrack(i, at) {
    if (!PLAYLIST.length || !stream) return;
    trackIndex = ((i % PLAYLIST.length) + PLAYLIST.length) % PLAYLIST.length;

    /* A held record shows in the bar but has no source attached, so
       pressing play does nothing rather than leaking the audio. */
    const t = PLAYLIST[trackIndex];
    if (window.bugHeld && window.bugHeld(t)) {
      stream.removeAttribute('src');
      stream.load();
      showTitle(trackIndex);
      return;
    }

    stream.src = t.src;
    showTitle(trackIndex);
    if (at) {
      stream.addEventListener('loadedmetadata', function once() {
        stream.removeEventListener('loadedmetadata', once);
        try { stream.currentTime = at; } catch (e) {}
      });
    }
  }

  function save() {
    if (!stream || !PLAYLIST.length) return;
    try {
      sessionStorage.setItem(STORE, JSON.stringify({
        i: trackIndex,
        t: stream.currentTime || 0,
        on: streamOn
      }));
    } catch (e) {}
  }

  if (stream && PLAYLIST.length) {
    let restored = null;
    try { restored = JSON.parse(sessionStorage.getItem(STORE) || 'null'); } catch (e) {}

    stream.muted = true;
    loadTrack(restored ? restored.i : 0, restored ? restored.t : 0);
    stream.play().catch(() => {});

    if (restored && restored.on) {
      // try to come back audible; revert cleanly if the browser says no
      stream.muted = false;
      stream.play().then(() => {
        streamOn = true;
        setStreamIcon();
      }).catch(() => {
        stream.muted = true;
        streamOn = false;
        setStreamIcon();
      });
    }

    stream.addEventListener('ended', () => {
      loadTrack(trackIndex + 1, 0);
      stream.play().catch(() => {});
    });

    // pagehide is more reliable than unload on mobile Safari
    window.addEventListener('pagehide', save);
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'hidden') save();
    });
    setInterval(save, 4000);
  } else {
    showTitle(0);
  }

  streamMute.addEventListener('click', () => {
    if (!stream || !PLAYLIST.length) {
      streamOn = !streamOn;      // still toggles so the control isn't dead
      setStreamIcon();
      return;
    }
    streamOn = !streamOn;
    stream.muted = !streamOn;
    if (streamOn) stream.play().catch(() => {});
    setStreamIcon();
    save();
  });

  /* Subscribe lives on its own page — /subscribe — so the legal
     disclosure sits where collection happens rather than under a
     field on every page of the site. */

  /* ── search ────────────────────────────────────────────
     Hands off to search.html, which loads the registries and
     does the lookup there. Keeping the index off every other
     page means the header stays light. */
  const searchInput = document.getElementById('search-input');
  const searchDots  = document.getElementById('search-dots');

  searchInput.addEventListener('input', () => {
    searchDots.classList.toggle('hide', searchInput.value.length > 0);
  });

  function runSearch() {
    const v = searchInput.value.trim();
    if (!v) { searchInput.focus(); return; }
    window.location.href = 'search#q=' + encodeURIComponent(v);
  }

  document.getElementById('search-btn').addEventListener('click', runSearch);
  searchInput.addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); runSearch(); }
  });

  /* arriving at results, put the term back in the field */
  if (PAGE === 'search') {
    const q = decodeURIComponent((location.hash || '').replace(/^#q?=?/, ''));
    if (q) {
      searchInput.value = q;
      searchDots.classList.add('hide');
    }
  }

  window.BUG = { setMenu, PAGE, IS_HOME };
})();
